// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSozDvw9xkuvIY8M0yAk_nlIq93tbRd5Y',
    appId: '1:697746036388:web:995a4938aa99f3a5c53831',
    messagingSenderId: '697746036388',
    projectId: 'phone-number-authenticat-8084b',
    authDomain: 'phone-number-authenticat-8084b.firebaseapp.com',
    storageBucket: 'phone-number-authenticat-8084b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdEfEFaN3u5uGhEPNpO4zklLNYQgdt1Jg',
    appId: '1:697746036388:android:9cb1aeb2e517db91c53831',
    messagingSenderId: '697746036388',
    projectId: 'phone-number-authenticat-8084b',
    storageBucket: 'phone-number-authenticat-8084b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQRvjPjeZi71hyX2dKb5alWSO9aJB6waA',
    appId: '1:697746036388:ios:6215cd243fa546dcc53831',
    messagingSenderId: '697746036388',
    projectId: 'phone-number-authenticat-8084b',
    storageBucket: 'phone-number-authenticat-8084b.appspot.com',
    iosBundleId: 'com.example.phoneNumberAuthentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQRvjPjeZi71hyX2dKb5alWSO9aJB6waA',
    appId: '1:697746036388:ios:15650a7ffc9ba18bc53831',
    messagingSenderId: '697746036388',
    projectId: 'phone-number-authenticat-8084b',
    storageBucket: 'phone-number-authenticat-8084b.appspot.com',
    iosBundleId: 'com.example.phoneNumberAuthentication.RunnerTests',
  );
}
